library(readr)
library(dplyr)
library(caret)
library(broom)
library(ggplot2)
setwd("C:\\Users\\Dell\\Desktop\\RStudio")
data <- read.csv("pizza_data_main.csv", header = TRUE)
head(data)
brand <- c("Dominos", "Pizza Hut", "Onesta")
price <- c("$1.00", "$2.00", "$3.00")
crust <- c("Thin", "Thick", "Stuffed")
toppings <- c("Pepperoni", "Mushroom", "Olives")
profiles <- expand.grid(brand = brand, price = price, crust = crust, toppings = toppings)
set.seed(123)  
profiles$rating <- sample(1:10, nrow(profiles), replace = TRUE)
print(profiles)
install.packages('conjoint')
library(conjoint)
result <- conjoint::caModel(y = profiles$rating, x = profiles[, 1:4])
print(result)