install.packages(c("dplyr", "psych", "tidyr", "GPArotation", "FactoMineR", "factoextra", "pheatmap"))
library(dplyr)
library(psych)
library(tidyr)
library(GPArotation)
library(FactoMineR)
library(factoextra)
library(pheatmap)
install.packages("cluster")
library(cluster)

setwd("C:\\Users\\HP\\Documents\\ns")
data <- read.csv("Survey.csv", header = TRUE)
sur_int=data[,18:46]
library(cluster) 
library(factoextra) 
show(sur_int) 
fviz_nbclust(sur_int,kmeans,method = "gap_stat") 
set.seed(123) 
km.res<-kmeans(sur_int,4,nstart = 25) 
fviz_cluster(km.res,data=sur_int,palette="jco", 
             ggtheme = theme_minimal()) 
res.hc <- hclust(dist(sur_int), method = "ward.D2") 
fviz_dend(res.hc,cex=0.5,k=4,palette = "jco") 
library(pheatmap) 
pheatmap(t(sur_int),cutree_cols = 4) 
